[package]
name = "vexations-fuzz"
version.workspace = true
publish = false
edition.workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
vexations-compiler = { path = "../vexations-compiler" }

[[bin]]
name = "fuzz_lexer"
path = "fuzz_targets/lexer.rs"
test = false
doc = false
