[coverage]
timeout = "300s"
minimum = 50
output-format = "Xml"
exclude-files = [
    "crates/vexations-integration-tests/**",
]
workspace = true
all-features = true
parallel = true

[coverage.output]
lcov = true
