[workspace]
resolver = "2"
members = [
    "crates/vexations-cli",
    "crates/vexations-compiler",
    "crates/vexations-generator",
    "crates/vexations-integration-tests",
]
default-members = [
    "crates/vexations-cli",
]


[workspace.package]
version = "0.1.0"
authors = ["Voxell Paladynee <voxellpaladynee@proton.me>"]
license = "EUPL-1.2"
repository = "https://github.com/Paladynee/vexations"
edition = "2024"

[workspace.dependencies]
vexations-cli = { path = "crates/vexations-cli" }
vexations-compiler = { path = "crates/vexations-compiler" }
vexations-generator = { path = "crates/vexations-generator" }

[profile.release]
opt-level = 3
lto = true
