[workspace]
members = [
    "crates/vexations-generator",
    "crates/vexations-compiler",
    "crates/vexations-cli",
    "crates/fuzz",
]
default-members = [
    "crates/vexations-cli",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]

[profile.release]
opt-level = 3
lto = true

[profile.fuzzing]
inherits = "release"
debug = true
