#!/usr/bin/env bash

rm -i vexations-*.ll

RUSTFLAGS='-Awarnings' cargo \
    clean -q
RUSTFLAGS='-Awarnings' cargo \
    rustc -q --release -- \
    --emit=llvm-ir -C link-dead-code "$@"

for thing in $(find target/*/deps -type f -name '*.ll'); do;
    echo "$thing"
    cp --update=none-fail "$thing" . 
    if (($?)); then
        echo "error $?: cp \"$thing\" ." >&2
    fi
done
