max_width = 80
imports_granularity = "Item"
edition = "2024"
style_edition = "2024"
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
wrap_comments = true
tab_spaces = 4
newline_style = "Unix"
reorder_imports = true
reorder_impl_items = false
reorder_modules = true
format_code_in_doc_comments = true
hard_tabs = false
comment_width = 80
format_macro_matchers = true
imports_layout = "Vertical"
merge_derives = true
overflow_delimited_expr = true
condense_wildcard_suffixes = true
remove_nested_parens = true
fn_params_layout = "Compressed"
match_arm_blocks = false
struct_lit_single_line = false